[project]
name = "hust-cv-project"
version = "0.1.0"
description = "HUST CV Project"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.6",
    "opencv-python>=4.12.0.88",
]
